before_script:
    - printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main\n" > /etc/apt/sources.list
    
    - echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list
    - echo 'APT::Default-Release "stable";' | tee -a /etc/apt/apt.conf.d/00local
    - cat /etc/apt/sources.list
    
    - apt-get update -qq
    - DEBIAN_FRONTEND=noninteractive apt-get -t testing install -y python3.6

    # #- apt-get install -y -qq python3-pip
    # - export CTAPIPE_VERSION=master
    # - pip3 install https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz
    # - pip3 install https://github.com/cta-observatory/ctapipe-extra/archive/$CTAPIPE_VERSION.tar.gz
    # - pip3 install -e .
    
run_tests:
    script:
        - echo "Yes!"
        # - pytest -vvs