before_script:
    - printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main\n" > /etc/apt/sources.list
    
    - echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list
    - echo 'APT::Default-Release "stable";' | tee -a /etc/apt/apt.conf.d/00local
    - cat /etc/apt/sources.list
    
    - apt-get update -qq
    - DEBIAN_FRONTEND=noninteractive apt-get -t testing install -yq python3.6

    - apt-get -t testing install -y -qq python3-pip
    - apt-get -t testing install -y -qq python3-pytest
    
    - pip3 install https://gitlab.mpcdf.mpg.de/ievo/ctapipe-mpp/-/archive/master/ctapipe-mpp-master.tar.gz
    - pip3 install https://github.com/cta-observatory/ctapipe-extra/archive/master.tar.gz
    - pip3 install -e .
    
run_tests:
    script:
        #  - echo "Yes!"
        - pytest-3 -vvs
