name: magicio
channels:
  - conda-forge
  - default
dependencies:
  - astropy~=5.0
  - python=3.9
  - ctapipe=0.17
  - eventio>=1.9.1
  - corsikaio
  - traitlets~=5.0,>=5.0.5
  - zeromq
  - ipython
  - numba
  - numpy>=1.18
  - numpydoc
  - pytest
  - pyyaml
  - scipy
  - zlib
  - pip
  - h5py
  - pip:
      - pytest_runner
      - uproot~=4.2