name: magicio
channels:
  - default
dependencies:
  - astropy>=4.0.5
  - python=3.8
  - conda-forge::ctapipe
  - conda-forge::eventio
  - conda-forge::corsikaio
  - traitlets
  - zeromq
  - ipython
  - numba
  - numpy>=1.18
  - numpydoc
  - pytest
  - pyyaml
  - scipy
  - zlib
  - pip
  - h5py
  - pip:
      - pytest_runner
      - uproot~=4.1
